---
spring:
    data:
        mongodb:
            host: ${MONGODB_HOST:localhost}
            port: ${MONGODB_PORT:27017}
            database: ${MONGODB_DATABASE:promptstore}
            username: ${MONGODB_USERNAME:db_user}
            password: ${MONGODB_PASSWORD:db_password}
server:
    port: ${SERVER_PORT:8091}
    servlet:
        context-path: ${SERVER_CONTEXT_PATH:/promptstore}