version: "3.8"
name: promptstore
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=promptstore
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - .\mongo-init:/docker-entrypoint-initdb.d
    networks:
      - "promptstore"

networks:
  promptstore: