version: "3.8"
name: promptstore
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=promptstore
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - .\mongo-init:/docker-entrypoint-initdb.d
    networks:
      - "promptstore"
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: prompt-catalog
    ports:
      - 8091:8091
    environment:
      - SERVER_CONTEXT_PATH=/promptstore
      - SECRET_KEY=Ydy2AoPokl8/NFluUbYUWcLVtjoT/Ch2Ga3PzKVYc+R+2IDM7DKmn1mza++Z2Voy
      - MONGODB_HOST=host.docker.internal
    networks:
      - "promptstore"


networks:
  promptstore: