openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8091/promptstore
  description: Generated server url
paths:
  /api/v1/prompts:
    post:
      tags:
      - prompt-controller
      summary: post-prompt
      description: creates a new prompt
      operationId: post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromptDefaultRequestDTO'
        required: true
      responses:
        "200":
          description: create prompt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromptDefaultResponseDTO'
        "400":
          description: bad request
components:
  schemas:
    PromptDefaultRequestDTO:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        content:
          type: string
    PromptDefaultResponseDTO:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        version:
          type: integer
          format: int32
        content:
          type: string
